[[constraint]]
  version = "0.0.3"
  name = "github.com/spf13/cobra"

[[constraint]]
  version = "0.8.0"
  name = "github.com/pkg/errors"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/spf13/viper"

[[constraint]]
  version = "1.0.6"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/brocaar/loraserver"

[[constraint]]
  branch = "master"
  name = "github.com/brocaar/lorawan"

[[override]]
  version = "1.14.0"
  name = "google.golang.org/grpc"

[[constraint]]
  version = "v1.2.2"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[prune]
  go-tests = true
  unused-packages = true
